version: '3.8'

services:
  php:
    build: .
    ports:
      - "8080/:80"
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:5.7
    
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_epasal_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1 #equivalent to True

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      PMA_HOST: mysql